### ISSUE TITLE
Add support for writing an OrderedDict to yaml file so we can control field order

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaData/YAML.jl#82]
It would be great if we could control field order when writing YAML files by using `OrderedDict`s instead of `Dict`s.

**Comment by CameronBieganek** [comment]
It turns out that all that needs to be changed is to replace `Dict` with `AbstractDict` in two places in the `writer.jl` file. I might make a PR at some point if I have the time to figure out the testing situation for this package.

**Comment by kescobo** [comment]
That would be great!

**Comment by mirkobunse** [comment]
Since the release v0.4.1 it is possible to write arbitrary subtypes of `AbstractDict`, for example to maintain field order with `OrderedDict` instances.

Beyond that, you can read arbitrary `AbstractDict` subtypes as of v0.4.2, so that you can maintain the field order also while reading.

I guess this PR is solved. Thanks @kescobo for the quick releases of these features!

**Comment by kescobo** [comment]
In that case, I'll close or, but @CameronBieganek if you disagree I'm happy to reopen.
